# TODO add collection params
dataset:
  dataset_count: 212368
  dataset_read_count_map: "[0:188441 1:17835 2:3130 3:1206 4:608 5:316 6:180 7:124 8:103 9:78 10:60 11:60 12:32 13:23
  14:16 15:15 16:14 17:10 18:8 19:4 20:9 21:10 22:4 23:5 24:6 25:3 26:6 27:4 28:2 29:2 30:3 31:4 32:2 34:2 35:2 36:1
  37:2 38:1 40:1 42:2 43:4 44:2 45:1 48:1 51:1 57:1 58:1 64:2 66:1 67:1 68:1 69:1 70:1 71:1 77:1 98:1 101:1 110:1 113:1
  123:1 154:1 176:1 194:1 197:1 233:1 253:1 362:1 381:1 520:1]"
  dataset_write_count_map: "[0:191518 1:7019 2:919 3:314 4:192 5:79 6:42 7:47 8:29 9:44 10:24 11:7 12:8 13:7 14:4 15:7
  16:4 17:6 18:4 19:4 20:2 21:4 22:3 24:1 25:1 26:2 28:3 29:1 30:1 32:1 34:1 35:1 36:1 38:1 42:1 46:1 53:1 56:1 58:1
  60:1 61:1 74:1 97:1 110:1 189:1 221:1 490:1]"
  dataset_slo_range_seconds: [5, 10000]
  dataset_env_count_map: "[DEVELOPMENT_ENV:3881 PERSONAL_ENV:348 PRODUCTION_ENV:185750 STAGING_ENV:7938 TESTING_ENV:1906
  UNKNOWN_ENV:418]"

system:
  system_count: 8415
  # Map {Number of input datasets: count systems}
  system_inputs_count_map: "[0:1072 1:2965 2:1671 3:844 4:515 5:301 6:203 7:128 8:95 9:72 10:69 11:47 12:46 13:32 14:14
  15:21 16:20 17:19 18:14 19:18 20:11 21:12 22:14 23:6 24:5 25:11 26:11 27:7 28:11 29:4 30:6 31:3 32:5 33:5 34:6 35:6
  36:3 37:1 38:4 39:3 40:2 41:1 42:2 43:4 44:1 45:2 46:2 47:5 48:4 49:4 50:2 51:1 52:1 53:1 55:2 56:1 57:1 58:1 59:2
  61:3 64:1 65:1 66:1 68:2 69:1 71:1 72:1 73:1 74:2 75:3 76:1 79:2 82:2 83:1 84:1 87:1 88:1 91:1 92:1 108:2 113:1 114:1
  120:1 121:1 125:1 126:1 127:1 141:1 153:1 154:1 157:2 162:1 167:1 168:1 169:1 182:1 183:2 184:1 186:1 187:2 189:1
  191:1 199:1 218:1 247:1 256:1 264:1 278:1 319:1 322:1 332:1 366:1 394:1 446:1 457:1 569:1 602:1 608:1 622:1 628:1
  768:1 1691:1 3022:1]"
  # Map {Number of output datasets: count systems}
  system_outputs_count_map: "[0:2602 1:3609 2:1149 3:361 4:225 5:127 6:78 7:31 8:42 9:29 10:22 11:17 12:12 13:11 14:7
  15:8 16:6 17:5 18:4 19:4 20:2 21:4 22:1 23:7 24:4 25:1 26:2 27:2 28:3 29:1 30:2 32:1 33:1 35:1 36:1 39:1 40:2 41:2
  42:1 44:2 46:1 48:2 49:2 50:2 51:1 53:2 57:1 59:1 60:1 64:1 70:1 74:1 75:1 77:1 78:1 132:1 144:1 217:1 248:1 431:1
  811:1]"
  system_criticality_proba_map: "[NOT_CRITICAL:0.7 CRITICAL_CAN_CAUSE_S0_OUTAGE:0.05 CRITICAL_SIGNIFICANT_RUN_RATE:0.1
  CRITICAL_OTHER:0.15]"
  system_env_count_map: "[DEVELOPMENT_ENV:3881 PERSONAL_ENV:348 PRODUCTION_ENV:185750 STAGING_ENV:7938 TESTING_ENV:1906
  UNKNOWN_ENV:418]"

dataset_collection:
  dataset_collection_count: 20028
  # Map {Number of datasets in dataset collection: dataset collection count}
  dataset_count_map: "[1:16559 2:604 3:231 4:145 5:240 6:105 7:147 8:82 9:47 10:61 11:41 12:26 13:15 14:7 15:20 16:16
  17:11 18:17 19:52 20:12 21:5 22:9 23:7 24:6 25:3 26:3 27:5 28:7 29:1 30:1 31:5 32:4 33:1 34:10 35:7 36:3 37:78 38:9
  39:21 40:3 41:1 42:9 43:11 44:1 46:4 47:1 48:1 49:9 51:3 52:13 54:1 55:35 56:41 57:1 58:1 61:2 63:1 64:1 65:10 67:2
  70:7 71:2 73:2 75:17 76:4 77:1 78:2 79:3 80:4 81:3 82:1 90:5 92:1 94:3 96:3 97:3 100:5 101:2 104:1 105:2 110:2 111:3
  112:226 113:1 114:1 115:8 116:5 117:10 118:25 119:58 120:16 121:12 122:22 123:3 124:9 125:2 126:4 127:3 128:2 129:1
  130:4 132:642 134:2 136:2 137:1 138:6 139:5 140:3 141:7 142:2 143:1 144:3 147:3 148:2 149:2 151:4 153:7 154:39 156:4
  158:9 159:1 160:1 161:1 162:2 164:2 165:1 168:2 175:1 176:6 189:1 203:1 347:1 399:1 1025:1]"

system_collection:
  system_collection_count: 1405
  # Map {Number of systems in system collection: system collection count}
  system_count_map: "[1:602 2:215 3:107 4:100 5:49 6:35 7:40 8:29 9:12 10:19 11:15 12:15 13:14 14:9 15:12 16:16 17:11
  18:7 19:6 20:4 21:10 22:6 23:3 24:4 25:4 26:4 27:4 29:4 30:2 31:3 32:3 34:1 36:2 37:2 38:2 39:1 40:3 42:3 43:1 45:2
  48:2 49:1 51:1 54:2 56:1 57:1 59:1 64:1 66:1 67:1 69:1 82:2 83:1 84:1 86:1 88:1 95:1 109:1 136:1 141:1 215:1]"

collection:
  collection_count: 10
  dataset_collection_count_map: "[2000:9 2028:1]"
  system_collection_count_map: "[140:9 145:1]"

data_processing:
  dataset_impact_proba_map: "[DOWN:0.01 SEVERELY_DEGRADED:0.04 DEGRADED:0.15 OPPORTUNITY_LOSS:0.3 NONE:0.5]"
  dataset_criticality_proba_map: "[IMMEDIATE:0.1 DAY:0.15 WEEK:0.2 EVENTUALLY:0.5 NEVER:0.05]"

data_integrity:
  restoration_range_seconds: [60, 259200]
  regeneration_range_seconds: [120, 259200]
  reconstruction_range_seconds: [180, 259200]
  volatality_proba_map: "[0:0.4 1:0.6]"
